compute_environment: LOCAL_MACHINE
# debug: false
distributed_type: 'MULTI_GPU' # 'NO' | 'MULTI_GPU' (set num_processes > 1) | 'TPU' (set tpu_use_cluster = True)
main_process_port: 29501
downcast_bf16: 'no'
gpu_ids: '0,1,2,3'
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 4
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
